name: Pull Request Checks

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  LANG: "nl_NL.UTF-8"
  LANGUAGE: "nl_NL:nl"
  LC_ALL: "nl_NL.UTF-8"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  hacs:
    permissions: write-all
    runs-on: "self-hosted"
    name: Test and validate
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - run: npm install
      
      - name: Run Tests
        run: npm run workflow
        
      - name: Run Jest
        uses: willcaul/jest-github-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          test-command: "npm run workflow"     

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3   
