name: Push to master checks

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  LANG: "nl_NL.UTF-8"
  LANGUAGE: "nl_NL:nl"
  LC_ALL: "nl_NL.UTF-8"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  hacs:
    runs-on: "self-hosted"
    name: Test and validate
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - run: npm install
       
      - name: Run Tests
        run: npm run coverage

      - name: Run Jest
        uses: willcaul/jest-github-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          test-command: "npm run coverage"
        
      - name: Get Latest Tag
        id: get_latest_tag
        run: |
          # Get the latest tag of the current branch
          LATEST_TAG=$(git describe --tags $(git rev-list --tags --max-count=1))
          echo "Latest tag is $LATEST_TAG"
          echo "::set-output name=latest_tag::$LATEST_TAG"
  
      - name: Update File with Latest Tag
        run: |
          # Update the file with the latest tag
          LATEST_TAG=${{ steps.get_latest_tag.outputs.latest_tag }}
          # Replace the line with the latest tag in your file (e.g., version.txt)
          sed -i "s/^sonar.projectVersion=.*/sonar.projectVersion=$LATEST_TAG/" sonar-project.properties

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONARCLOUD_TOKEN }}

      - name: HACS validation
        uses: hacs/action@main
        with:
          category: "plugin"
          ignore: brands

      # - name: Automatic GitHub Release
      #   uses: marcokreeft87/github-action-npm-release@1.0.0

      # - name: Print release output
      #   if: ${{ steps.release.outputs.released == 'true' }}
      #   run: echo Release ID ${{ steps.release.outputs.release_id }}